source 'https://rubygems.org'
ruby '2.1.1'

# See: https://github.com/rails/rails/issues/13164
gem 'i18n',                   github: 'svenfuchs/i18n',
                              ref: '8fc94e7e9ec20396e974b0549cf499662238bf56'

gem 'rails',                  '4.0.5'
gem 'puma',                   '2.8.2'
gem 'secure_headers',         '1.1.1'
gem 'jquery-rails',           '3.1.0'
gem 'jquery-ui-rails',        '4.2.1'
gem 'turbolinks',             '2.2.2'
gem 'slim-rails',             '2.1.4'
gem 'pg',                     '0.17.1'
gem 'sass-rails',             '4.0.3'
gem 'coffee-rails',           '4.0.1'
gem 'uglifier',               '2.5.0'
gem 'rack-canonical-host',    '0.1.0'
gem 'rack-timeout',           '0.0.4'
gem 'simple_form',            '3.0.2'
gem 'enumerize',              '0.8.0'
gem 'flutie',                 '2.0.0'
gem 'devise',                 '3.2.4'

group :production do
  gem 'rails_12factor',       '0.0.2'
  gem 'rollbar',              '0.12.18'
  gem 'newrelic_rpm',         '3.8.1.221'
end

group :development do
  gem 'foreman',              '0.63.0'
  gem 'jumpup',               '0.0.5'
  gem 'jumpup-heroku',        github: 'Helabs/jumpup-heroku'
  gem 'jumpup-hipchat',       '0.2.0'
  gem 'better_errors',        '1.1.0'
  gem 'binding_of_caller',    '0.7.2'
  gem 'letter_opener',        '1.2.0'
  gem 'letter_opener_web',    '1.2.0'
  gem 'bullet',               '4.9.0'
  gem 'quiet_assets',         '1.0.2'
end

group :test do
  gem 'shoulda-matchers',     '2.6.1'
  gem 'simplecov',            '0.8.2', require: false
  gem 'email_spec',           '1.5.0'
  gem 'database_cleaner',     '1.2.0'
  gem 'guard-rspec',          '4.2.9', require: false
end

group :development, :test do
  gem 'rspec-rails',          '3.0.0'
  gem 'factory_girl_rails',   '4.4.1'
  gem 'pry-rails',            '0.3.2'
  gem 'dotenv-rails',         '0.11.1'
  gem 'awesome_print',        '1.2.0'
end
